services:
  api:
    container_name: floral-fiesta
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - mysql
    networks:
      - net

  mysql:
    container_name: floral-fiesta-db
    image: mysql
    ports:
        - "3306:3306"
    restart: always
    environment:
        MYSQL_DATABASE: db
        MYSQL_USER: springuser
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    networks:
        - net

networks:
  net:
    name: net



